#**Week-5 Assignment**
##**SQL Murder Mystery**

---

There's been a `Murder` in `SQL City`! The `SQL Murder Mystery` is designed to be both a self-directed lesson to learn SQL concepts and commands and a fun game for experienced SQL users to solve an intriguing crime.<br>

A crime has taken place and the detective needs our help. The detective gave us the crime scene report, but we somehow lost it. We vaguely remember that the crime was a murder that occurred sometime on `Jan.15, 2018`, and that it took place in `SQL City`.

---

## **Importing Libraries & DataBase**

First we will be importing multiple libraries:
* `import pandas as pd`: Imports the pandas library and allows it to be used with the alias `pd`.
* `import sqlite3 as sql`: Imports the sqlite3 library and allows it to be used with the alias `sql`.
* `import requests`: Imports the requests library, which is used for making HTTP requests.

In [1]:
import pandas as pd
import sqlite3 as sql
import requests
pd.set_option('display.max_colwidth', None)

In order to access the `sql-murder-mystery.db` , I have uploaded it to Github repository.
* [Raw File](https://raw.githubusercontent.com/ArijitDhali/PrepInsta-DA-Week-5/main/sql-murder-mystery.db): Sets the URL where the `sql-murder-mystery.db` SQL database file is hosted on GitHub.

In [2]:
url = 'https://github.com/vignay21/Prepinsta/raw/main/PrepInsta-Week5/Murder%20Mystery/sql-murder-mystery.db'

**Downloading the File**
- `r = requests.get(url, allow_redirects=True)`: Fetches the content from the specified URL (`url`) using the `requests.get()` method. The `allow_redirects=True` parameter allows following redirections, if any.
- `open('sql-murder-mystery.db', 'wb').write(r.content)`: Writes the content (`r.content`) fetched from the URL into a file named `sql-murder-mystery.db` in binary write mode. This effectively downloads the database file from GitHub and saves it locally in the current working directory of the Python script.

**Connecting to the Database**
- `con = sql.connect('sql-murder-mystery.db')`: Establishes a connection to the SQLite database file (`sql-murder-mystery.db`) using the `sql.connect()` method from the `sqlite3` library. Assumes that the file has been successfully downloaded and resides in the same directory where this Python script is executed. The `con` variable holds the connection object to interact with the SQLite database.


In [3]:
r = requests.get(url, allow_redirects=True)
open('sql-murder-mystery.db', 'wb').write(r.content)
con = sql.connect('sql-murder-mystery.db')                # connect to the downloaded file

In order to check the contents of the database we will use the particular command.

In [4]:
data = '''
SELECT name
FROM sqlite_master
WHERE type='table';
'''
pd.read_sql_query(data, con)

name
0      crime_scene_report
1         drivers_license
2                  person
3  facebook_event_checkin
4               interview
5      get_fit_now_member
6    get_fit_now_check_in
7                  income
8                solution

##**Checking & Viewing Database**

Before we process or manipulate with the tables in the database, we need to get familiarized with the datasets present in the database. <br> View their `Table` names and `Column` names.

### **Table 1:** crime_scene_report

Viewing the `crime_scene_report` table.
<br>Columns:
* `date`
* `type`
* `description`
* `city`

In [5]:
# Query to view top 5 rows from the data
csr = '''
SELECT *
FROM crime_scene_report
LIMIT 5
'''
pd.read_sql_query(csr, con)

date     type                                              description  \
0  20180115  robbery        A Man Dressed as Spider-Man Is on a Robbery Spree   
1  20180115   murder                        Life? Dont talk to me about life.   
2  20180115   murder      Mama, I killed a man, put a gun against his head...   
3  20180215   murder                               REDACTED REDACTED REDACTED   
4  20180215   murder  Someone killed the guard! He took an arrow to the knee!   

       city  
0       NYC  
1    Albany  
2      Reno  
3  SQL City  
4  SQL City

### **Table 2:** drivers_license


Viewing the `drivers_license` table.
<br>Columns:
* `id`
* `age`
* `height`
* `eye_color`
* `hair_color`
* `gender`
* `plate_number`
* `car_make`
* `car_model`

In [6]:
# Query to view top 5 rows from the data
dli = '''
SELECT *
FROM drivers_license
LIMIT 5
'''
pd.read_sql_query(dli, con)

id  age  height eye_color hair_color  gender plate_number  car_make  \
0  100280   72      57     brown        red    male       P24L4U     Acura   
1  100460   63      72     brown      brown  female       XF02T6  Cadillac   
2  101029   62      74     green      green  female       VKY5KR     Scion   
3  101198   43      54     amber      brown  female       Y5NZ08    Nissan   
4  101255   18      79      blue       grey  female       5162Z1     Lexus   

  car_model  
0       MDX  
1       SRX  
2        xB  
3     Rogue  
4        GS

### **Table 3:** person

Viewing the `person` table.
<br>Columns:
* `id`
* `name`
* `license_id`
* `address_number`
* `address_street_name`
* `ssn`


In [7]:
# Query to view top 5 rows from the data
per = '''
SELECT *
FROM person
LIMIT 5
'''
pd.read_sql_query(per, con)

id                 name  license_id  address_number address_street_name  \
0  10000   Christoper Peteuil      993845             624        Bankhall Ave   
1  10007  Kourtney Calderwood      861794            2791       Gustavus Blvd   
2  10010            Muoi Cary      385336             741     Northwestern Dr   
3  10016          Era Moselle      431897            1987       Wood Glade St   
4  10025         Trena Hornby      550890             276       Daws Hill Way   

         ssn  
0  747714076  
1  477972044  
2  828638512  
3  614621061  
4  223877684

### **Table 4:** facebook_event_checkin

Viewing the `facebook_event_checkin` table.
<br>Columns:
* `person_id`
* `event_id`
* `event_name`
* `date`


In [8]:
# Query to view top 5 rows from the data
fech = '''
SELECT *
FROM facebook_event_checkin
LIMIT 5
'''
pd.read_sql_query(fech, con)

person_id  event_id  \
0      28508      5880   
1      63713      3865   
2      63713      3999   
3      63713      6436   
4      82998      4470   

                                                            event_name  \
0                      Nudists are people who wear one-button suits.\n   
1  but that's because it's the best book on anything for the layman.\n   
2                             If Murphy's Law can go wrong, it will.\n   
3     Old programmers never die.  They just branch to a new address.\n   
4                                 Help a swallow land at Capistrano.\n   

       date  
0  20170913  
1  20171009  
2  20170502  
3  20170926  
4  20171022

### **Table 5:** interview

Viewing the `interview` table.
<br>Columns:
* `person_id`
* `transcript`


In [9]:
# Query to view top 5 rows from the data
inte = '''
SELECT *
FROM interview
LIMIT 5
'''
pd.read_sql_query(inte, con)

person_id  \
0      28508   
1      63713   
2      86208   
3      35267   
4      33856   

                                                                transcript  
0                                      ‘I deny it!’ said the March Hare.\n  
1                                                                       \n  
2                            way, and the whole party swam to the shore.\n  
3  lessons in here? Why, there’s hardly room for YOU, and no room at all\n  
4                                                                       \n

### **Table 6:** get_fit_now_member

Viewing the `get_fit_now_member` table.
<br>Columns:
* `id`
* `person_id`
* `name`
* `membership_start_date`
* `membership_status`


In [10]:
# Query to view top 5 rows from the data
gfnm = '''
SELECT *
FROM get_fit_now_member
LIMIT 5
'''
pd.read_sql_query(gfnm, con)

id  person_id                name  membership_start_date  \
0  NL318      65076     Everette Koepke               20170926   
1  AOE21      39426        Noe Locascio               20171005   
2  2PN28      63823  Jeromy Heitschmidt               20180215   
3  0YJ24      80651      Waneta Wellard               20171206   
4  3A08L      32858        Mei Bianchin               20170401   

  membership_status  
0              gold  
1           regular  
2            silver  
3              gold  
4            silver

### **Table 7:** get_fit_now_check_in

Viewing the `get_fit_now_check_in` table.
<br>Columns:
* `membership_id`
* `check_in_date`
* `chech_in_time`
* `chech_out_time`

In [11]:
# Query to view top 5 rows from the data
gfnci = '''
SELECT *
FROM get_fit_now_check_in
LIMIT 5
'''
pd.read_sql_query(gfnci, con)

membership_id  check_in_date  check_in_time  check_out_time
0         NL318       20180212            329             365
1         NL318       20170811            469             920
2         NL318       20180429            506             554
3         NL318       20180128            124             759
4         NL318       20171027            418            1019

### **Table 8:** income

Viewing the `income` table.
<br>Columns:
* `ssn`
* `annual_income`

In [12]:
# Query to view top 5 rows from the data
inc = '''
SELECT *
FROM income
LIMIT 5
'''
pd.read_sql_query(inc, con)

ssn  annual_income
0  100009868          52200
1  100169584          64500
2  100300433          74400
3  100355733          35900
4  100366269          73000

### **Table 9:** solution

Viewing the `solution` table.
<br>Columns:
* `user`
* `value`

In [13]:
# Query to view top 5 rows from the data
sol = '''
SELECT *
FROM solution
LIMIT 5
'''
pd.read_sql_query(sol, con)

Empty DataFrame
Columns: [user, value]
Index: []

## **Clue To The Mystery**
Till now we can only remember the date and place of murder.
*  `Date` : 15 January, 2018
*  `Place` : SQL City

In [14]:
# Viewing the Murder happened in SQL City on 15 January 2018
crime_scene = '''
SELECT *
FROM crime_scene_report
WHERE city = "SQL City"
AND date = 20180115
AND type = 'murder'
'''
pd.read_sql_query(crime_scene, con)

date    type  \
0  20180115  murder   

                                                                                                                                                                                 description  \
0  Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".   

       city  
0  SQL City

## **Solving Murder Mystery**

Till now we can only remember the date and place of murder.
*  `Date` : 15 January, 2018
*  `Place` : SQL City

In [15]:
# Viewing the crime report evidance

query_1 = '''
SELECT *
FROM crime_scene_report
WHERE type = 'murder'
AND city = 'SQL City'
AND date = 20180115
;
'''
pd.read_sql_query(query_1, con)

date    type  \
0  20180115  murder   

                                                                                                                                                                                 description  \
0  Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".   

       city  
0  SQL City

We will first get familiarize with the dataset of the `person` table.

In [16]:
# Check out the table

query_2 = '''
SELECT *
FROM person
LIMIT 5
;
'''
pd.read_sql_query(query_2, con)

id                 name  license_id  address_number address_street_name  \
0  10000   Christoper Peteuil      993845             624        Bankhall Ave   
1  10007  Kourtney Calderwood      861794            2791       Gustavus Blvd   
2  10010            Muoi Cary      385336             741     Northwestern Dr   
3  10016          Era Moselle      431897            1987       Wood Glade St   
4  10025         Trena Hornby      550890             276       Daws Hill Way   

         ssn  
0  747714076  
1  477972044  
2  828638512  
3  614621061  
4  223877684

In order to find the first witness, we will search database with the matching parameters.
<Br>First witness lives on `LAST house of Northwestern Dr`.
<br>To find the person we will perform the query with following steps:
1. Select the `person` table
2. Find `address_street_name` - `Northwestern Dr`
3. Find the first name in `Descending` order

In [17]:
# Security footage shows that there were 2 witnesses.
# The first witness : Place - Last house on "Northwestern Dr".

# Finding the first witness, we got a clue that they live in LAST house of Northwestern Dr

query_3 = '''
SELECT *
FROM person
WHERE address_street_name = 'Northwestern Dr'
ORDER BY address_number DESC
LIMIT 1
;
'''
pd.read_sql_query(query_3, con)

id            name  license_id  address_number address_street_name  \
0  14887  Morty Schapiro      118009            4919     Northwestern Dr   

         ssn  
0  111564949

In order to find the second witness, we will search database with the matching parameters.
<Br>First witness lives on `somewhere in Franklin Ave` and her name is `Annabel`.
<br>To find the person we will perform the query with following steps:
1. Select the `person` table
2. Find `address_street_name` - `Franklin Ave`
3. Find the name like `Annabel`

In [18]:
# Security footage shows that there were 2 witnesses.
# The second witness: Name - Annabel
#                     Place - Somewhere on "Franklin Ave".

# Finding the second witness, we got a clue that they live in Franklin Ave and her name is Annabel

query_4 = '''
SELECT *
FROM person
WHERE address_street_name = 'Franklin Ave'
AND name LIKE '%Annabel%'
;
'''
pd.read_sql_query(query_4, con)

id            name  license_id  address_number address_street_name  \
0  16371  Annabel Miller      490173             103        Franklin Ave   

         ssn  
0  318771143

After retrieving their `id`, hear about their `interview` and note for clues.
<br> We will note the transcript of witnesses of id `14887` and `16371`.

In [19]:
# Now listening to the interview of two persons with ID 14887,16371

query_5 = '''
SELECT *
FROM interview
WHERE person_id IN (14887,16371)
;
'''
pd.read_sql_query(query_5, con)

person_id  \
0      14887   
1      16371   

                                                                                                                                                                                                                        transcript  
0  I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".  
1                                                                                                            I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.

According to first witness, the culprit has following characteristics:
* `Gold` Member of `Get Fit Now Gym`
* Bag with membership number `starting with 48Z`
* Has car `number plate including H42W`
* Is a `male`

To find the person we will perform the query with following steps:
1. Select the `get_fit_now_member` table
2. Find `membership_status` - `Gold`
3. Find the `id` like `48Z`


In [20]:
# ID 14887 Keynotes : Gold Member of GET FIT NOW GYM.
#                     Membership Number Starting with 48Z
#                     Has car with number plate including H42W
# ID 16371 Keynotes : Gym Checkin on 9 Jan 2018

# Validating data with the notes of witness 1 with GYM Details

query_6 = '''
SELECT *
FROM get_fit_now_member
WHERE membership_status = 'gold'
AND id LIKE '48Z%'
;
'''
pd.read_sql_query(query_6, con)

id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

4. Select `drivers_license` table.
5. Find plate_number like `H42W`
6. The culprit should be `male`

In [21]:
# Validating data with the notes of witness 1 with CAR Details

query_7 = '''
SELECT *
FROM drivers_license
WHERE plate_number LIKE '%H42W%'
AND gender = 'male'
;
'''
pd.read_sql_query(query_7, con)

id  age  height eye_color hair_color gender plate_number   car_make  \
0  423327   30      70     brown      brown   male       0H42W2  Chevrolet   
1  664760   21      71     black      black   male       4H42WR     Nissan   

  car_model  
0  Spark LS  
1    Altima

* Inner joining `get_fit_now_member` with `drivers_license` table.
* Search the `culprit over same parameters` with witness 1's note.


In [22]:
# Validating data with the notes of witness 1 with CAR and GYM Details

query_8 = '''
SELECT *
FROM person as p
INNER JOIN drivers_license as dl on p.license_id = dl.id
WHERE plate_number LIKE '%H42W%'
AND gender = 'male'
;
'''
pd.read_sql_query(query_8, con)

id            name  license_id  address_number    address_street_name  \
0  51739  Tushar Chandra      664760             312                 Phi St   
1  67318   Jeremy Bowers      423327             530  Washington Pl, Apt 3A   

         ssn      id  age  height eye_color hair_color gender plate_number  \
0  137882671  664760   21      71     black      black   male       4H42WR   
1  871539279  423327   30      70     brown      brown   male       0H42W2   

    car_make car_model  
0     Nissan    Altima  
1  Chevrolet  Spark LS

According to second witness, the culprit has following characteristics:
* Member of `Get Fit Now Gym`
* He checked in Gym on `9 Jan 2018`

<br>To find the person we will perform the query with following steps:
1. Select the `get_fit_now_check_in` table
2. Find date - `20180109`

In [23]:
# Validating data with the notes of witness 2 with GYM CHECKIN Details

query_9 = '''
SELECT *
FROM get_fit_now_check_in
WHERE check_in_date = 20180109
;
'''
pd.read_sql_query(query_9, con)

membership_id  check_in_date  check_in_time  check_out_time
0         X0643       20180109            957            1164
1         UK1F2       20180109            344             518
2         XTE42       20180109            486            1124
3         1AE2H       20180109            461             944
4         6LSTG       20180109            399             515
5         7MWHJ       20180109            273             885
6         GE5Q8       20180109            367             959
7         48Z7A       20180109           1600            1730
8         48Z55       20180109           1530            1700
9         90081       20180109           1600            1700

Looking out for personal details using the `Inner Join` of `person` to `drivers_license`.

In [24]:
# Innerjoinig two tables

query_10 = '''
SELECT p.*
FROM drivers_license as dl
INNER JOIN person as p on dl.id = p.license_id
WHERE plate_number LIKE '%H42W%'
AND gender = 'male'
;
'''
pd.read_sql_query(query_10, con)

id            name  license_id  address_number    address_street_name  \
0  51739  Tushar Chandra      664760             312                 Phi St   
1  67318   Jeremy Bowers      423327             530  Washington Pl, Apt 3A   

         ssn  
0  137882671  
1  871539279

Finding out the final culprit after validating the notes given by two witnesses.
<br> Using the `Inner Join`, we find tha actual culprit of the murder.

In [27]:
# ID 14887 Keynotes : Gold Member of GET FIT NOW GYM.
#                     Membership Number Starting with 48Z
#                     Has car with number plate including H42W
# ID 16371 Keynotes : Gym Checkin on 9 Jan 2018

# Validating data with the notes of 2 witnesses : Looking after the common factor of GYM, Car Details and GYM Checking

query_11 = '''
SELECT p.*,gfn.membership_start_date,gfn.membership_status
FROM person as p
INNER JOIN drivers_license as dl on dl.id = p.license_id
INNER JOIN get_fit_now_member as gfn on p.id = gfn.person_id
INNER JOIN get_fit_now_check_in as gfc on gfc.membership_id = gfn.id
WHERE plate_number LIKE '%H42W%'
AND gender = 'male'
AND membership_status = 'gold'
AND gfn.id LIKE '48Z%'
AND check_in_date = 20180109;
'''
pd.read_sql_query(query_11, con)

id           name  license_id  address_number    address_street_name  \
0  67318  Jeremy Bowers      423327             530  Washington Pl, Apt 3A   

         ssn  membership_start_date membership_status  
0  871539279               20160101              gold

This following query is used to check whether the solution is correct or not.<br>
However, the only drawback is it can run once only, after first execution.

In [28]:
check_1 = '''
INSERT INTO solution VALUES (1, 'Jeremy Bowers');
'''
pd.read_sql_query(check_1, con)

TypeError: 'NoneType' object is not iterable

In [29]:
check_1a = '''
SELECT value FROM solution;
'''
pd.read_sql_query(check_1a, con)

value
0  Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge, try querying the interview transcript of the murderer to find the real villain behind this crime. If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries. Use this same INSERT statement with your new suspect to check your answer.

**JEREMY BOWERS is the murderer.**

Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge, try querying the interview transcript of the murderer to find the real villain behind this crime. If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries. Use this same INSERT statement with your new suspect to check your answer.

## **Finding the Master-Mind**

To find the mastermind behind all these mess, wee need to interview `JEREMY BOWERS` <br>
We will check for his `transcripts` in `interview` table

In [30]:
# Interviewing the culprit of the murder

mind_0='''
SELECT *
FROM interview
WHERE person_id = 67318
;
'''
pd.read_sql_query(mind_0, con)

person_id  \
0      67318   

                                                                                                                                                                                                                                           transcript  
0  I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n

As per `JEREMY BOWERS`' interview, he concluded the characteristics of the mastermind.<br>
The characteristic:
* `Gender` - Female
* `Height` - Between 65" and 67"
* `Hair` - Red
* `Car` - Tesla Model S
* `Concert` - SQL Symphony Concert [3 Times in December]

To find the person we will perform the query with following steps:
1. Select the table `drivers_license`
2. Search for `hair_color` - `red`
3. Search for `car_make` - `Tesla` and `car_model` - `Model S`
4. Ranging the `age` between `65" and 67"`

In [31]:
# Keynotes from the interview : Gender - Female
#                               Height - Between 65" and 67"
#                               Hair - Red
#                               Car - Tesla Model S
#                               Concert - SQL Symphony Concert x3 in December

# Validating the data using details such as CAR Details, Height and Hair Color

mind_1='''
SELECT *
FROM drivers_license
WHERE car_make = 'Tesla'
AND car_model = 'Model S'
AND hair_color = 'red'
AND height BETWEEN 65 AND 67
;
'''
pd.read_sql_query(mind_1, con)

id  age  height eye_color hair_color  gender plate_number car_make  \
0  202298   68      66     green        red  female       500123    Tesla   
1  291182   65      66      blue        red  female       08CM64    Tesla   
2  918773   48      65     black        red  female       917UU3    Tesla   

  car_model  
0   Model S  
1   Model S  
2   Model S

5. Select `facebook_event_checkin`
6. Search for `event_name` - `SQL Symphony Concert`
7. Ranging the `date` between `20171201 and 20171231`

In [32]:
# Validating the data using CONCERT CHECKIN

mind_2='''
SELECT *
FROM facebook_event_checkin
WHERE event_name = 'SQL Symphony Concert'
AND date BETWEEN 20171201 AND 20171231
;
'''
pd.read_sql_query(mind_2, con)

person_id  event_id            event_name      date
0       62596      1143  SQL Symphony Concert  20171225
1       19260      1143  SQL Symphony Concert  20171214
2       58898      1143  SQL Symphony Concert  20171220
3       69699      1143  SQL Symphony Concert  20171214
4       19292      1143  SQL Symphony Concert  20171213
5       43366      1143  SQL Symphony Concert  20171207
6       92343      1143  SQL Symphony Concert  20171212
7       28582      1143  SQL Symphony Concert  20171220
8       28582      1143  SQL Symphony Concert  20171215
9       81526      1143  SQL Symphony Concert  20171202
10      24397      1143  SQL Symphony Concert  20171208
11      11173      1143  SQL Symphony Concert  20171223
12      79312      1143  SQL Symphony Concert  20171203
13      69325      1143  SQL Symphony Concert  20171206
14      24556      1143  SQL Symphony Concert  20171207
15      24556      1143  SQL Symphony Concert  20171221
16      24556      1143  SQL Symphony Concert  20171224
17      99716      1143  SQL Symphony Concert  20171206
18      99716      1143  SQL Symphony Concert  20171212
19      99716      1143  SQL Symphony Concert  20171229
20      67318      1143  SQL Symphony Concert  20171206

We will now Inner Join the `person`, `drivers_license`, `facebook_event_checkin` and `income` tables on common parameters to find mastermind.<br>
Also check if the person has a good `annual_income`.

In [33]:
# Keynotes from the culprit interview : Gender - Female
#                               Height - Between 65" and 67"
#                               Hair - Red
#                               Car - Tesla Model S
#                               Concert - SQL Symphony Concert x3 in December

# Validating the data using CONCERT CHECKIN, CAR DETAILS and PERSONAL CHARACTERISTICS

mind_3='''
SELECT p.*, dl.car_make, dl.car_model, dl.hair_color, dl.height, inc.annual_income
FROM person as p
INNER JOIN income as inc on inc.ssn = p.ssn
INNER JOIN drivers_license as dl on dl.id = p.license_id
INNER JOIN facebook_event_checkin as fec on p.id = fec.person_id
WHERE car_make = 'Tesla'
AND car_model = 'Model S'
AND hair_color = 'red'
AND height BETWEEN 65 AND 67
AND event_name = 'SQL Symphony Concert'
AND date BETWEEN 20171201 AND 20171231
;
'''
pd.read_sql_query(mind_3, con)

id              name  license_id  address_number address_street_name  \
0  99716  Miranda Priestly      202298            1883          Golden Ave   
1  99716  Miranda Priestly      202298            1883          Golden Ave   
2  99716  Miranda Priestly      202298            1883          Golden Ave   

         ssn car_make car_model hair_color  height  annual_income  
0  987756388    Tesla   Model S        red      66         310000  
1  987756388    Tesla   Model S        red      66         310000  
2  987756388    Tesla   Model S        red      66         310000

Congrats, you found the brains behind the murder! Everyone in SQL City hails you as the greatest SQL detective of all time. Time to break out the champagne!


This following query is used to check whether the solution is correct or not.<br>
However, the only drawback is it can run once only, after first execution.

In [34]:
check_2 = '''
INSERT INTO solution VALUES (1, 'Miranda Priestly');
'''
pd.read_sql_query(check_2, con)

TypeError: 'NoneType' object is not iterable

In [35]:
check_2a = '''
SELECT value FROM solution;
'''
pd.read_sql_query(check_2a, con)

value
0  Congrats, you found the brains behind the murder! Everyone in SQL City hails you as the greatest SQL detective of all time. Time to break out the champagne!

**MIRANDA PRIESTLY** is the mastermind behind the murder. Her `income` justifies that she has enough wealth to hire **JEREMY BOWERS** and visited the `SQL Symphony Concert` 3 times in `December`.